#Here you can prescribe the messages that will be displayed to the player when interacting with a resident
#If you want the message to be colored, you must specify the color element code before the message.

Messages:
   msg1: 'Привет'
   msg2: 'У меня есть интересные вещи'
   msg3: 'Как дела ?'
   msg4: 'Пока!'

#Here you can set the name
Customname:
   name: '&4Пушистик'
#Here you can specify a message when a VillagerEntity is spawned
Spawn:
   message: '&bЖитель заспавнен!'

